/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type GamblerStruct = { id: AddressLike; choice: BigNumberish };

export type GamblerStructOutput = [id: string, choice: bigint] & {
  id: string;
  choice: bigint;
};

export type DisplayInfoStruct = {
  id: AddressLike;
  host: AddressLike;
  gameType: BigNumberish;
  wager: BigNumberish;
  isActive: boolean;
  gamblers: GamblerStruct[];
};

export type DisplayInfoStructOutput = [
  id: string,
  host: string,
  gameType: bigint,
  wager: bigint,
  isActive: boolean,
  gamblers: GamblerStructOutput[]
] & {
  id: string;
  host: string;
  gameType: bigint;
  wager: bigint;
  isActive: boolean;
  gamblers: GamblerStructOutput[];
};

export type RecordStruct = {
  from: AddressLike;
  to: AddressLike;
  game: AddressLike;
  value: BigNumberish;
  recordType: BigNumberish;
};

export type RecordStructOutput = [
  from: string,
  to: string,
  game: string,
  value: bigint,
  recordType: bigint
] & {
  from: string;
  to: string;
  game: string;
  value: bigint;
  recordType: bigint;
};

export interface CasinoInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bankrollGetBalance"
      | "bankrollGetTransactionRecords"
      | "createGame"
      | "getGame"
      | "getGames"
      | "playGame"
      | "playGameWithDefaultHost"
      | "rawFulfillRandomWords"
      | "requestRandom"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CompleteGame_Event"
      | "CreateGame_Event"
      | "VrfRequest_Event"
      | "VrfResponse_Event"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bankrollGetBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bankrollGetTransactionRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createGame",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGame",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getGames", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "playGame",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playGameWithDefaultHost",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomWords",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandom",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "bankrollGetBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bankrollGetTransactionRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGames", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "playGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playGameWithDefaultHost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rawFulfillRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRandom",
    data: BytesLike
  ): Result;
}

export namespace CompleteGame_EventEvent {
  export type InputTuple = [game: AddressLike, winner: AddressLike];
  export type OutputTuple = [game: string, winner: string];
  export interface OutputObject {
    game: string;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreateGame_EventEvent {
  export type InputTuple = [game: DisplayInfoStruct];
  export type OutputTuple = [game: DisplayInfoStructOutput];
  export interface OutputObject {
    game: DisplayInfoStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VrfRequest_EventEvent {
  export type InputTuple = [game: AddressLike, requestId: BigNumberish];
  export type OutputTuple = [game: string, requestId: bigint];
  export interface OutputObject {
    game: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VrfResponse_EventEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    randomWords: BigNumberish[]
  ];
  export type OutputTuple = [requestId: bigint, randomWords: bigint[]];
  export interface OutputObject {
    requestId: bigint;
    randomWords: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Casino extends BaseContract {
  connect(runner?: ContractRunner | null): BaseContract;
  attach(addressOrName: AddressLike): this;
  deployed(): Promise<this>;

  interface: CasinoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bankrollGetBalance: TypedContractMethod<[], [bigint], "view">;

  bankrollGetTransactionRecords: TypedContractMethod<
    [],
    [RecordStructOutput[]],
    "view"
  >;

  createGame: TypedContractMethod<
    [gameType: BigNumberish, choice: BigNumberish],
    [void],
    "payable"
  >;

  getGame: TypedContractMethod<
    [targetGame: AddressLike],
    [DisplayInfoStructOutput],
    "view"
  >;

  getGames: TypedContractMethod<[], [DisplayInfoStructOutput[]], "view">;

  playGame: TypedContractMethod<
    [targetGame: AddressLike, choice: BigNumberish],
    [void],
    "payable"
  >;

  playGameWithDefaultHost: TypedContractMethod<
    [gameType: BigNumberish, choice: BigNumberish],
    [void],
    "payable"
  >;

  rawFulfillRandomWords: TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  requestRandom: TypedContractMethod<
    [gameAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bankrollGetBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bankrollGetTransactionRecords"
  ): TypedContractMethod<[], [RecordStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<
    [gameType: BigNumberish, choice: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<
    [targetGame: AddressLike],
    [DisplayInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGames"
  ): TypedContractMethod<[], [DisplayInfoStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "playGame"
  ): TypedContractMethod<
    [targetGame: AddressLike, choice: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "playGameWithDefaultHost"
  ): TypedContractMethod<
    [gameType: BigNumberish, choice: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "rawFulfillRandomWords"
  ): TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestRandom"
  ): TypedContractMethod<[gameAddress: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CompleteGame_Event"
  ): TypedContractEvent<
    CompleteGame_EventEvent.InputTuple,
    CompleteGame_EventEvent.OutputTuple,
    CompleteGame_EventEvent.OutputObject
  >;
  getEvent(
    key: "CreateGame_Event"
  ): TypedContractEvent<
    CreateGame_EventEvent.InputTuple,
    CreateGame_EventEvent.OutputTuple,
    CreateGame_EventEvent.OutputObject
  >;
  getEvent(
    key: "VrfRequest_Event"
  ): TypedContractEvent<
    VrfRequest_EventEvent.InputTuple,
    VrfRequest_EventEvent.OutputTuple,
    VrfRequest_EventEvent.OutputObject
  >;
  getEvent(
    key: "VrfResponse_Event"
  ): TypedContractEvent<
    VrfResponse_EventEvent.InputTuple,
    VrfResponse_EventEvent.OutputTuple,
    VrfResponse_EventEvent.OutputObject
  >;

  filters: {
    "CompleteGame_Event(address,address)": TypedContractEvent<
      CompleteGame_EventEvent.InputTuple,
      CompleteGame_EventEvent.OutputTuple,
      CompleteGame_EventEvent.OutputObject
    >;
    CompleteGame_Event: TypedContractEvent<
      CompleteGame_EventEvent.InputTuple,
      CompleteGame_EventEvent.OutputTuple,
      CompleteGame_EventEvent.OutputObject
    >;

    "CreateGame_Event(tuple)": TypedContractEvent<
      CreateGame_EventEvent.InputTuple,
      CreateGame_EventEvent.OutputTuple,
      CreateGame_EventEvent.OutputObject
    >;
    CreateGame_Event: TypedContractEvent<
      CreateGame_EventEvent.InputTuple,
      CreateGame_EventEvent.OutputTuple,
      CreateGame_EventEvent.OutputObject
    >;

    "VrfRequest_Event(address,uint256)": TypedContractEvent<
      VrfRequest_EventEvent.InputTuple,
      VrfRequest_EventEvent.OutputTuple,
      VrfRequest_EventEvent.OutputObject
    >;
    VrfRequest_Event: TypedContractEvent<
      VrfRequest_EventEvent.InputTuple,
      VrfRequest_EventEvent.OutputTuple,
      VrfRequest_EventEvent.OutputObject
    >;

    "VrfResponse_Event(uint256,uint256[])": TypedContractEvent<
      VrfResponse_EventEvent.InputTuple,
      VrfResponse_EventEvent.OutputTuple,
      VrfResponse_EventEvent.OutputObject
    >;
    VrfResponse_Event: TypedContractEvent<
      VrfResponse_EventEvent.InputTuple,
      VrfResponse_EventEvent.OutputTuple,
      VrfResponse_EventEvent.OutputObject
    >;
  };
}
